
REQUIREMENTS_FILENAME = 'requirements.txt'
REQUIREMENTS_DEV_FILENAME = 'requirements-dev.txt'

DEV_REQUIREMENTS = [
    'Sphinx',
    'pytest>=3.7.2',
    'flake8'
]


DOCS_DIRNAME = 'docs'
TESTS_DIRNAME = 'tests'

GITIGNORE_FILENAME = '.gitignore'
README_FILENAME = 'README.md'
TODO_FILENAME = 'TODO.md'
LICENSE_FILENAME = 'LICENSE'
CONFTEST_FILENAME = 'conftest.py'
STANDALONE_SAMPLE_FILENAME = 'sample_standalone.py'
STANDALONE_SAMPLE_TEST_FILENAME = 'sample_standalone_test.py'
TOX_FILENAME = 'tox.ini'

STANDALONE_REPO_FILES_TO_GEN = [
    README_FILENAME,
    GITIGNORE_FILENAME,
    TODO_FILENAME,
    CONFTEST_FILENAME,
    STANDALONE_SAMPLE_FILENAME,
    STANDALONE_SAMPLE_TEST_FILENAME,
    TOX_FILENAME
]

STANDALONE_REPO_DIRS_TO_GEN = [
    DOCS_DIRNAME,
    TESTS_DIRNAME
]