
REQUIREMENTS_FILENAME = 'requirements.txt'
REQUIREMENTS_DEV_FILENAME = 'requirements-dev.txt'


REQUIREMENTS = [
    'pbr',
    'setuptools',
]

REQUIREMENTS_DEV = [
    'Sphinx',
    'pytest',
    'flake8'
]


TEMPLATES_DIRNAME = 'templates'

DOCS_DIRNAME = 'docs'
TESTS_DIRNAME = 'tests'
REPOASSIST_DIRNAME = 'repoassist'

GITIGNORE_FILENAME = '.gitignore'
README_FILENAME = 'README.md'
TODO_FILENAME = 'TODO.md'
LICENSE_FILENAME = 'LICENSE'
CONFTEST_FILENAME = 'conftest.py'
STANDALONE_SAMPLE_FILENAME = 'sample_standalone.py'
STANDALONE_SAMPLE_TEST_FILENAME = 'sample_standalone_test.py'
TOX_FILENAME = 'tox.ini'
PYINIT_FILENAME = '__init__.py'
SAMPLE_MODULE_FILENAME = 'module.py'
REPOASSIST_MAIN_FILENAME = 'repoassist_main.py'
REPOASSIST_TARGET_MAIN_FILENAME = '__main__.py'
COLREQS_FILENAME = 'colreqs.py'

STANDALONE_REPO_FILES_TO_GEN = [
    README_FILENAME,
    GITIGNORE_FILENAME,
    TODO_FILENAME,
    CONFTEST_FILENAME,
    STANDALONE_SAMPLE_FILENAME,
    STANDALONE_SAMPLE_TEST_FILENAME,
    TOX_FILENAME,
    PYINIT_FILENAME,
    REQUIREMENTS_FILENAME,
    REQUIREMENTS_DEV_FILENAME
]

STANDALONE_REPO_DIRS_TO_GEN = [
    DOCS_DIRNAME,
    TESTS_DIRNAME,
    REPOASSIST_DIRNAME
]

REPOASSIST_FILES = [
    PYINIT_FILENAME,
    REPOASSIST_MAIN_FILENAME,
    COLREQS_FILENAME,
]